# Generated by Django 5.2 on 2025-04-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_shipment_estimated_arrival_time_shipment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='route',
            name='cost',
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('at_warehouse', 'На складе'), ('in_transit', 'В перевозке'), ('delivered', 'Доставлен'), ('returned', 'Возвращен'), ('lost', 'Утерян')], default='created', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='route',
            name='travel_time',
            field=models.DurationField(help_text='Пример: 1 02:30:00 = 1 день, 2 часа, 30 минут', verbose_name='Время в пути'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='departure_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время отправления'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='shipments', to='logistics.item', verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('loading', 'Загрузка'), ('in_transit', 'В пути'), ('arrived', 'Прибыла'), ('unloading', 'Разгрузка'), ('unloaded', 'Разгружена'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='created', max_length=20, verbose_name='Статус'),
        ),
    ]
